services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    restart: unless-stopped

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1
    ports:
      - "${KAFKA1_PORT}:${KAFKA1_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA1_ADVERTISED_INTERNAL},EXTERNAL://${KAFKA1_ADVERTISED_EXTERNAL}
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:${KAFKA1_INTERNAL_PORT},EXTERNAL://0.0.0.0:${KAFKA1_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      - zookeeper
    restart: unless-stopped

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2
    ports:
      - "${KAFKA2_PORT}:${KAFKA2_PORT}"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA2_ADVERTISED_INTERNAL},EXTERNAL://${KAFKA2_ADVERTISED_EXTERNAL}
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:${KAFKA2_INTERNAL_PORT},EXTERNAL://0.0.0.0:${KAFKA2_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      - zookeeper
    restart: unless-stopped

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka3
    ports:
      - "${KAFKA3_PORT}:${KAFKA3_PORT}"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA3_ADVERTISED_INTERNAL},EXTERNAL://${KAFKA3_ADVERTISED_EXTERNAL}
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:${KAFKA3_INTERNAL_PORT},EXTERNAL://0.0.0.0:${KAFKA3_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      - zookeeper
    restart: unless-stopped
